resource_group_name   = "harnessdemorg"
location              = "East US"
storage_account_name  = "harnessdemosa"
app_service_plan_name = "harnessdemoasp"
function_app_name     = "harnessdemofa"
runtime               = "dotnet"
subscription_id       = "a327a41f-a5e9-458f-b5bb-0dc87483eb85"
