subscription_id       = "a327a41f-a5e9-458f-b5bb-0dc87483eb85"
resource_group_name   = "example-rg"
location              = "East US"
server_name           = "harnessdevdb"
admin_username        = "pgadmin"
admin_password        = "P@ssword123!"
sku_name              = "B_Standard_B1ms"
storage_mb            = 65536
backup_retention_days = 7
availability_zone     = "1"
delegated_subnet_id   = "/subscriptions/a327a41f-a5e9-458f-b5bb-0dc87483eb85/resourceGroups/Rancher-rancher-quickstart/providers/Microsoft.Network/virtualNetworks/Rancher-network/subnets/rancher-quickstart-internal"
private_dns_zone_id   = "/subscriptions/a327a41f-a5e9-458f-b5bb-0dc87483eb85/resourceGroups/aks-cof/providers/Microsoft.Network/privateDnsZones/privatelink.postgres.database.azure.com"
environment           = "dev"
