subscription_id       = "a327a41f-a5e9-458f-b5bb-0dc87483eb85"
location              = "Central India"
resource_group_name   = "harnessprodci"
prefix                = "harnessprodci"
storage_account_name  = "harnessprodsaci"
sql_admin             = "sqladminuser"
sql_password          = "Welcome@12345678"
